{
    'name': 'Marriage Registration',
    'version': '1.0',
    'category': 'Services',
    'summary': 'Marriage Registration Management System',
    'sequence': 1,
    'author': 'Your Company',
    'website': 'https://www.yourcompany.com',
    'depends': ['base', 'mail'],
    'data': [
        'security/marriage_security.xml',
        'security/ir.model.access.csv',
        'data/marriage_sequence.xml',
        'data/payment_sequence.xml',
        'data/document_data.xml',
        'views/assets.xml',
        'views/document_type_views.xml',
        'views/payment_views.xml',
        'views/marriage_views.xml',
    ],
    'demo': [],
    'installable': True,
    'application': True,
    'auto_install': False,
    'license': 'LGPL-3',
} 